name: music_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  audio_service: ^0.18.18
  metadata_god: ^1.1.0
  audio_service_mpris: ^0.2.0
  flutter_acrylic: ^1.1.4
  just_audio: ^0.10.5
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: ^1.2.1
  font_awesome_flutter: ^10.12.0
  http: ^1.6.0
  flutter_discord_rpc: ^1.1.0
  shared_preferences: ^2.2.2
  go_router: ^17.0.1
  signals: ^6.3.0
  signals_flutter: ^6.3.0
  permission_handler: ^12.0.1
  super_sliver_list: ^0.4.1
  bitsdojo_window: ^0.1.6
  flutter_single_instance: ^1.7.0
  nativeapi: ^0.1.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Iosevka Nerd Font
      fonts:
        - asset: assets/fonts/IosevkaNerdFont-Regular.ttf
        - asset: assets/fonts/IosevkaNerdFont-Bold.ttf
          weight: 700
  assets:
    - assets/app_icon.png
